export const content = {
  hero: {
    heading: "Welcome Aboard.",
    subheading: "You're one of WildLog's first Founding Captains. You'll help shape the app before anyone else.",
    cta: "Get Started →",
    ctaSupport: "Takes about 10 minutes",
  },
  progress: {
    heading: "Captain Progress",
    storageKey: "wildlog-captain-progress-v2",
    items: [
      "Create your account",
      "Create your first group",
      "Invite your crew",
      "Start your season",
      "Log your first catch",
    ],
  },
  onboardingVideo: {
    heading: "See the first run",
    description: "A fast walkthrough from account setup to first catch.",
    src: "/assets/onboarding-walkthrough.mp4",
    poster: "/assets/hero.jpg",
    captions: "/assets/onboarding-walkthrough.vtt",
  },
  missions: [
    {
      number: 1,
      title: "Create Your WildLog Account",
      why: "Your account unlocks your Captain tools and keeps your catch history with you.",
      description: "Download the app and sign up. Takes 2 minutes.",
      estTime: "2 min",
      screenshotAlt: "App login screen",
      cta: "Login or Sign Up",
      ctaHref: "https://wildlog-spearfish.vercel.app/login",
    },
    {
      number: 2,
      title: "Create Your First Group",
      why: "Your Group is your dive crew. Everything in WildLog happens inside Groups.",
      description: "Name your crew and become the group owner. You set the rules.",
      estTime: "3 min",
      screenshotAlt: "Groups screen",
      cta: "Create a Group",
      ctaHref: "https://wildlog-spearfish.vercel.app/groups",
    },
    {
      number: 3,
      title: "Invite Your Crew",
      why: "Invites turn your private setup into a real crew leaderboard.",
      description: "Share your group's invite link. This is where it starts.",
      estTime: "5–10 min",
      screenshotAlt: "Invite/share screen",
      cta: "Invite Crew",
      ctaHref: "https://wildlog-spearfish.vercel.app/groups?invite=1",
    },
    {
      number: 4,
      title: "Start Your Season",
      why: "A Season gives the crew a clear start line, end date, and reason to keep logging.",
      description: "Set a name, duration, and start date. Your crew competes within it.",
      estTime: "1 min",
      screenshotAlt: "Season creation",
      cta: "Start Season",
      ctaHref: "https://wildlog-spearfish.vercel.app/seasons",
    },
    {
      number: 5,
      title: "Log Your First Catch",
      why: "The first catch proves the whole flow works and shows your crew what good logging looks like.",
      description: "Catch something? Log it. Share it. Build momentum in your group.",
      estTime: "5 min",
      screenshotAlt: "Logging screen",
      cta: "Add Catch",
      ctaHref: "https://wildlog-spearfish.vercel.app/catches/new",
    },
  ],
  captainTips: {
    heading: "Captain Tips",
    items: [
      "Keep your first Group small (3–10 people)",
      "Invite active dive buddies first",
      "Log every trip",
      "Share feedback often",
    ],
  },
  feedback: {
    heading: "We're Learning Too",
    description: "Tell us what works, what breaks, and what you'd love to see next.",
    cta: "Send Beta Feedback",
    whatsappMessage: "Hey Sage, I wanted to share feedback on WildLog...",
  },
  betaExpectations: {
    heading: "This is a real beta",
    items: [
      "You'll probably find bugs.",
      "You'll definitely have ideas.",
      "Every piece of feedback directly influences what we build next.",
      "Thank you for helping shape WildLog.",
    ],
  },
  finalMission: {
    heading: "You're Ready",
    description: "Mission this week:",
    items: [
      "Create one Group",
      "Invite three friends",
      "Log your first catch",
      "Tell us one thing we should improve",
    ],
  },
  contact: {
    heading: "Questions?",
    description: "Message us directly anytime.",
    whatsapp: "YOUR_WHATSAPP_NUMBER_HERE",
    email: "YOUR_EMAIL_HERE",
    cta: "Need Help?",
  },
};
